import { GameDefinition } from '@/types';

export const games: GameDefinition[] = [
  {
    id: 'reaction-showdown',
    name: 'Reaction Showdown',
    description: 'Tap when the signal appears! Fastest reflex wins. Watch out for trick rounds.',
    emoji: '⚡',
    color: 'from-yellow-500 to-orange-500',
    category: 'reflex',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'finger-cricket',
    name: 'Finger Cricket',
    description: 'Pick a number 1-6 simultaneously. Match = out! Classic hand cricket, digitized.',
    emoji: '🏏',
    color: 'from-green-500 to-emerald-500',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'dots-and-boxes',
    name: 'Dots & Boxes',
    description: 'Draw lines between dots. Complete a box to score. Simple but deeply strategic.',
    emoji: '📦',
    color: 'from-blue-500 to-indigo-500',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'color-clash',
    name: 'Color Clash',
    description: 'Match the target color as closely as possible. Score based on color accuracy!',
    emoji: '🎨',
    color: 'from-pink-500 to-purple-500',
    category: 'perception',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'memory-flip',
    name: 'Memory Flip Race',
    description: 'Flip cards to find matching pairs. Take turns, most matches wins!',
    emoji: '🃏',
    color: 'from-violet-500 to-purple-500',
    category: 'memory',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'type-racer',
    name: 'Type Racer Duel',
    description: 'Race to type a passage! See each other\'s cursors in real-time.',
    emoji: '⌨️',
    color: 'from-cyan-500 to-blue-500',
    category: 'reflex',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'sync-or-sink',
    name: 'Sync or Sink',
    description: 'Answer the same question — if you match, you score! Think alike to win.',
    emoji: '🧠',
    color: 'from-amber-500 to-yellow-500',
    category: 'social',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'word-bomb',
    name: 'Word Bomb',
    description: 'Type a word containing the shown letters before your fuse runs out!',
    emoji: '💣',
    color: 'from-red-500 to-orange-500',
    category: 'word',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'maze-race',
    name: 'Maze Race',
    description: 'Navigate a randomly generated maze. See your opponent. First to exit wins!',
    emoji: '🏁',
    color: 'from-teal-500 to-green-500',
    category: 'reflex',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'pattern-pulse',
    name: 'Pattern Pulse',
    description: 'Remember and repeat the color sequence. Speed increases! Who survives longer?',
    emoji: '🔴',
    color: 'from-rose-500 to-red-500',
    category: 'memory',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'emoji-charades',
    name: 'Emoji Charades',
    description: 'Describe a word using only emojis. Your partner guesses! Swap roles each round.',
    emoji: '😄',
    color: 'from-orange-500 to-amber-500',
    category: 'social',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'trivia-showdown',
    name: 'Trivia Showdown',
    description: 'Answer trivia questions from Open Trivia DB. Faster correct answer = more points!',
    emoji: '❓',
    color: 'from-indigo-500 to-blue-500',
    category: 'knowledge',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'doodle-duel',
    name: 'Doodle Duel',
    description: 'Draw a word, swap drawings, guess what the other drew. Artistic chaos!',
    emoji: '✏️',
    color: 'from-lime-500 to-green-500',
    category: 'creative',
    minPlayers: 2,
    maxPlayers: 2,
  },
  {
    id: 'jigsaw-together',
    name: 'Jigsaw Together',
    description: 'Solve a jigsaw puzzle collaboratively. Drag pieces into place together!',
    emoji: '🧩',
    color: 'from-sky-500 to-blue-500',
    category: 'co-op',
    minPlayers: 2,
    maxPlayers: 2,
  },
];

export function getGame(id: string): GameDefinition | undefined {
  return games.find((g) => g.id === id);
}
